import type { Metadata } from "next";
import "../globals.css";
import Navbar from "./components/navbar";

export const metadata: Metadata = {
  title: "EpiDrive",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <div className="lg:pl-72 m-4">
        {children}
        </div>
      </body>
    </html>
  );
}
