import type { Metadata } from "next";
import "../globals.css";
import Navbar from "./components/navbar"; // Importation du composant Navbar

// Métadonnées pour la page du backoffice
export const metadata: Metadata = {
  title: "EpiDrive",
  description: "Generated by create next app",
};

/**
 * Layout principal pour le backoffice.
 * Inclut la Navbar et un conteneur principal pour le contenu.
 */
export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {/* Navbar */}
        <Navbar />
        {/* Contenu dynamique */}
        <div className="lg:pl-72 m-4">
          {children}
        </div>
      </body>
    </html>
  );
}
