// src/app/layout.tsx
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ReactNode } from "react";
import ClientSessionWrapper from "../components/ClientSessionWrapper";
import ClientNavbarWrapper from "@/components/ClientNavbarWrapper";
import ClientFooterWrapper from "@/components/ClientFooterWrapper";
import { CartProvider } from "@/context/CartContext";

// Définition des polices locales
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Export des métadonnées
export const metadata: Metadata = {
  title: "EpiDrive",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="fr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientSessionWrapper>
          <CartProvider>
            <ClientNavbarWrapper />
            {children}
            <ClientFooterWrapper />
          </CartProvider>
        </ClientSessionWrapper>
      </body>
    </html>
  );
}
