name: Simulated CD Workflow

on:
  push:
    branches:
      - main

jobs:
  simulate-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          IMAGE_TAG="simulated-deployment:${{ github.run_id }}"
          docker build -t $IMAGE_TAG .

      - name: Run Docker Container
        run: |
          IMAGE_TAG="simulated-deployment:${{ github.run_id }}"
          docker run -d -p 3000:3000 --name simulated-app-${{ github.run_id }} $IMAGE_TAG

      - name: Wait for Application to Start
        run: sleep 20

      - name: Health Check
        run: |
          curl -f http://localhost:3000/health || exit 1
          echo "Health check passed for simulated deployment"

      - name: Check Docker Logs
        if: failure()
        run: docker logs simulated-app-${{ github.run_id }}

      - name: Clean Up
        run: |
          docker stop simulated-app-${{ github.run_id }}
          docker rm simulated-app-${{ github.run_id }}
          IMAGE_TAG="simulated-deployment:${{ github.run_id }}"
          docker rmi $IMAGE_TAG
