name: Simulated CD Workflow

on:
  push:
    branches:
      - main

jobs:
  simulate-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t simulated-deployment:latest -t your-dockerhub-username/simulated-deployment:latest .

      - name: Push Docker Image
        run: docker push your-dockerhub-username/simulated-deployment:latest

      - name: Run Docker Container
        run: docker run -d -p 3000:3000 --name simulated-app your-dockerhub-username/simulated-deployment:latest

      - name: Wait for Application to Start
        run: sleep 20

      - name: Health Check
        run: |
          curl -f http://localhost:3000/health || exit 1
          echo "Health check passed for simulated deployment"

      - name: Check Docker Logs
        if: failure()
        run: docker logs simulated-app

      - name: Clean Up
        run: |
          docker stop simulated-app
          docker rm simulated-app
          docker rmi your-dockerhub-username/simulated-deployment:latest
