name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  SHADOW_DATABASE_URL: ${{ secrets.SHADOW_DATABASE_URL }}
  MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
  MYSQL_USER: ${{ secrets.MYSQL_USER }}
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: epidrive
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # 1. Mettre à jour le système
      - name: Update System
        run: sudo apt-get update

      # 2. Installer Docker Compose
      - name: Install Docker Compose
        run: sudo apt-get install -y docker-compose

      # 3. Récupérer le dépôt
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 4. Configurer Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      # 5. Mettre en cache les modules Node.js
      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: ./src/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules

      # 6. Installer les dépendances
      - name: Install Dependencies
        run: npm install
        working-directory: ./src
      
      # 7. Vérifier la qualité du code
      - name: Lint and Fix
        run: npm run lint --fix || true
        working-directory: ./src

      # 8. Générer le client Prisma (si applicable)
      - name: Generate Prisma Client
        run: npx prisma generate
        working-directory: ./src

      # 9. Vérifier les migrations Prisma
      - name: Check Prisma Migrations
        run: npx prisma migrate dev --name init
        working-directory: ./src

      # 10. Build du projet
      - name: Build Project
        run: npm run build
        working-directory: ./src
