name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/epidrive:latest

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      docker:
        image: epidrive:latest
        options: --health-cmd='curl -f http://localhost/ || exit 1' --health-interval=30s --health-timeout=10s --health-retries=3
        ports:
          - 80:80
    steps:
      - name: Wait for Docker container to be healthy
        run: |
          for i in {1..10}; do
            if [ "$(docker inspect --format='{{.State.Health.Status}}' ${{ secrets.DOCKER_USERNAME }}/epidrive:latest)" == "healthy" ]; then
              exit 0
            fi
            sleep 10
          done
          exit 1

      - name: Run Application Tests
        run: curl -f http://localhost/ || exit 1

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref_type == 'tag'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Application
        env:
          DATABASE_URL: "mysql://user:password@db:3306/epidrive"
        run: echo "Deploying application Epidrive ..."
